imu-path: /media/rebeater/hd_data2/workspace/raw_data/car/20210114/Rover/IMU/adis16460.imd
imu-parameter-cfg: /media/rebeater/hd_data2/workspace/raw_data/car/20210114/Rover/IMU/imu_m39_parameter.yml
gnss-path: /media/rebeater/hd_data2/workspace/raw_data/car/20210114/Rover/GNSS/taidou.txt.gga
output-path: /media/rebeater/hd_data2/workspace/raw_data/car/20210114/Rover/Output/taidou_adis16460.rslt
start-time: 378815
end-time: -1
imu-data-rate: 200
#--------------------------------------------------------------------------------#
alignment-mode: 0 # 0: useGiven 1: Moving 2: Stationary(not implement yet)
alignment-epoch:
  - 2140 #　GPS week
  - 378815.0000 # second of week
  - 40.0876202296  # latitude
  -  116.2411937620   # longitude
  - 33.123  # height
  - -2.488 # v_n (m/s)
  - -6.419 # v_e m/s
  - 0.098 # v_d
  -  -0.56753340 # roll (deg)
  - 4.13367016    # pitch (deg)
  - 247.77730322  # yaw (deg)
init-pos-std:
  - 0.004 # m
  - 0.001 # m
  - 0.005 # m
init-vel-std:
  - 0 # m/s
  - 0 # m/s
  - 0 # m/s
init-atti-std:
  - 0.027  # deg
  - 0.027  # deg
  - 0.03  # deg for SPP is so 不靠谱
alignment-moving-vel: 3 # m/s threshold velocity for moving align
nhc-enable: false
nhc-hz: 20
install-angle:
  - 0
  - 4.0150
  - -0.44
nhc-std:
  - 0.5
  - 0.5
zupt-enable: true
zupta-enable: true

#--------------------------------------------------------------------------------#
imu-format: 0
# IMU_FORMAT_IMD = 0
# IMU_FORMAT_IMUTXT = 1
gnss-format: 6  #
# GNSS_TXT_POS_7 = 0,
# GNSS_BIN_POS_7 = 1,
# GNSS_TXT_POS_14 = 2,
# GNSS_BIN_POS_14 = 3,
# RTKLIB_TXT_POS = 4,
# GNSS_TXT_POS_VEL = 5,
# GNSS_TXT_GGA = 6,
# RESERVED = 67,
gnss-data-rate: 1
antenna-level-arm:
  - 1.5 #　forward
  - 0.2 # right
  - -0.86 # down
#--------------------------------------------------------------------------------#
odo-enable: 0 # 0: disable odometer 1: enable odometer
odo-wheel-radius: 0 # 车轮半径
odo-level-arm:
  - -0.5
  - 1
  - 0.5
#--------------------------------------------------------------------------------#
outage-enable: true
outage-start: 379216
outage-stop: -1
outage-time: 30
outage-step: 100
#--------------------------------------------------------------------------------#