imu-path: /media/rebeater/hd_data2/workspace/raw_data/robot/20200625/ADI_210625_452483.adi.imutxt
imu-parameter-cfg: /home/rebeater/CLionProjects/psins/yaml/imu_adis16460_parameter.yml
gnss-path: /media/rebeater/hd_data2/workspace/raw_data/robot/20200625/GNSS_210625_452483.gps.gpstxt
odo-path: /media/rebeater/hd_data2/workspace/raw_data/robot/20200625/VEL_210625_452483.vel.veltxt
output-path: /media/rebeater/hd_data2/workspace/raw_data/robot/20200625/RSLT_210625_452483.post.lcv2.nav
start-time: 452738
end-time: 453738
imu-data-rate: 128
#--------------------------------------------------------------------------------#
alignment-mode: 1 # 0: useGiven 1: Moving 2: Stationary(not implement yet)
alignment-epoch:
  - 2140 #　GPS week
  - 378819.0000 # second of week
  - 40.0875433430  # latitude
  - 116.2408255479   # longitude
  - 33.465   # height
  - -3.010  # v_n (m/s)
  -  -8.750  # v_e m/s
  - 0.108 # v_d
  - -0.164042568 # roll (deg)
  -  3.78730506    # pitch (deg)
  -   250.90865325    # yaw (deg)
init-pos-std:
  - 4 # m
  - 1 # m
  - 5 # m
init-vel-std:
  - 0.4 # m/s
  - 0.5 # m/s
  - 0.6 # m/s
init-atti-std:
  - 4  # deg
  - 2  # deg
  - 5  # deg for SPP is so 不靠谱
alignment-moving-vel: 3 # m/s threshold velocity for moving align
nhc-enable: false
nhc-hz: 20
install-angle:
  - 0
  - -1.55
  - -0.395
nhc-std:
  - 0.5
  - 0.5
zupt-enable: true
zupta-enable: true

#--------------------------------------------------------------------------------#
imu-format: 1
# IMU_FORMAT_IMD = 0
# IMU_FORMAT_IMUTXT = 1
gnss-format: 7  #
# GNSS_TXT_POS_7 = 0,
# GNSS_BIN_POS_7 = 1,
# GNSS_TXT_POS_14 = 2,
# GNSS_BIN_POS_14 = 3,
# RTKLIB_TXT_POS = 4,
# GNSS_TXT_POS_VEL = 5,
# GNSS_TXT_GGA = 6,
# RESERVED = 7,
gnss-data-rate: 1
antenna-level-arm:
  - 0.2 #　forward
  - 0.0 # right
  - -0.3 # down
#--------------------------------------------------------------------------------#
odo-kd-std: 0.1
odo-kd-init: 1.37 # 里程计初始比例因子
odo-enable: 1 # 0: disable odometer 1: enable odometer
odo-wheel-radius: 0 # 车轮半径
odo-level-arm:
  - -0
  - 0
  - 00
#--------------------------------------------------------------------------------#
outage-enable: false
outage-start: 379216
outage-stop: -1
outage-time: 30
outage-step: 100
#--------------------------------------------------------------------------------#