imu-path: /media/rebeater/hd_data2/workspace/raw_data/robot/20211110/RAW_211111_357327.RAW.imutxt
imu-parameter-cfg: ../yaml/imu_kyimu102Na0_parameter.yml
gnss-path: /media/rebeater/hd_data2/workspace/raw_data/robot/20211110/RAW_211111_357327.RAW.gnsstxt
odo-path: /media/rebeater/hd_data2/workspace/raw_data/robot/20211110/RAW_211111_357327.RAW.veltxt
output-path: /media/rebeater/hd_data2/workspace/raw_data/robot/20211110/RAW_211111_357327.RAW.post.nav
start-time: 357446.000
end-time: -1
imu-data-rate: 200
#--------------------------------------------------------------------------------#
alignment-mode: 1 # 0: useGiven 1: Moving 2: Stationary(not implement yet)
alignment-epoch:
  - 0 #　GPS week
  - 456300.0000 # second of week
  - 30.4447873696  # latitude
  -  114.4718632476   # longitude
  - 20.910  # height
  - 0 # v_n (m/s)
  - 0 # v_e
  - 0 # v_d
  -  0.85252308 # roll (deg)
  - -2.03396435    # pitch (deg)
  - 185.69625052  # yaw (deg)
init-pos-std:
  - 15.45 # m
  - 15.1 # m
  - 15.5 # m
init-vel-std:
  - 1 # m/s
  - 1 # m/s
  - 1 # m/s
init-atti-std:
  - 30.27  # deg
  - 40.27  # deg
  - 30.3  # deg for SPP is so 不靠谱
alignment-moving-vel: 3 # m/s threshold velocity for moving align
nhc-enable: false
nhc-hz: 20
install-angle:
  - 0
  - -0
  - -0.0
nhc-std:
  - 0.5
  - 0.5
zupt-enable: true
zupta-enable: true

#--------------------------------------------------------------------------------#
imu-format: 1
# IMU_FORMAT_IMD = 0
# IMU_FORMAT_IMUTXT = 1

gnss-format: 6  #
# GNSS_TXT_POS_7 = 0,
# GNSS_BIN_POS_7 = 1,
# GNSS_TXT_POS_14 = 2,
# GNSS_BIN_POS_14 = 3,
# RTKLIB_TXT_POS = 4,
# GNSS_TXT_POS_VEL = 5,
# RESERVED = 6,
gnss-data-rate: 1
antenna-level-arm:
  - 0.2 #　forward
  - -0.17 # right
  - -0.3 # down
#--------------------------------------------------------------------------------#
odo-kd-std: 0.00001
odo-kd-init: 0.85 # 里程计初始比例因子
odo-enable: true # 0: disable odometer 1: enable odometer
odo-wheel-radius: 0 # 车轮半径
odo-var: 0.3
odo-level-arm:
  - -0
  - 0
  - 00
#--------------------------------------------------------------------------------#
#--------------------------------------------------------------------------------#
outage-enable: false
outage-start: 379216
outage-stop: -1
outage-time: 30
outage-step: 100
#--------------------------------------------------------------------------------#